# config/sidekiq.yml
# REDIS SERVER: redis-server

# SIDEKIQ SERVER : bundle exec sidekiq -C ./config/sidekiq.yml

# MY_SAMPLE_APP : nodemon -L --exec “./restart_rails.sh"

:verbose: false
:concurrency: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
:timeout: 30
:max_retries: 1
:logfile: ./log/sidekiq.log
:queues:
  - [low_priority, 1]
  - [high_priority, 2] # high priority