# config/sidekiq.yml
---
:verbose: false
:concurrency: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
:timeout: 30
:max_retries: 1
:logfile: ./log/sidekiq.log
:queues:
  - [low_priority, 1]
  - [high_priority, 2] # high priority